"""empty message

Revision ID: 1749bbc82d0b
Revises: 5c88ac8b486e
Create Date: 2025-12-06 01:15:38.664021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1749bbc82d0b'
down_revision: Union[str, None] = '5c88ac8b486e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_qty', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_qty')
    # ### end Alembic commands ###
