"""empty message

Revision ID: 80a7703f262b
Revises: 
Create Date: 2025-10-18 15:41:57.457898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a7703f262b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('addresses', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('addresses', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
